# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-08-10 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='goods.GoodsCategory', verbose_name='从属类别'),
        ),
    ]
