# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-08-10 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200810_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='default_image_url',
        ),
        migrations.AddField(
            model_name='sku',
            name='default_image',
            field=models.ImageField(blank=True, default='', max_length=200, null=True, upload_to='', verbose_name='默认图片'),
        ),
    ]
